### ISSUE TITLE
Elastic APM Go agent

### ISSUE THREAD

**Issue by axw** [interactive-solutions/go-apm-agent#1]
Just wanted to let you know, in case you're not already aware, that Elastic has plans to develop a Go agent: https://discuss.elastic.co/t/apm-roadmap/113071. This is likely still a while away, so I don't want to discourage you from developing your own. It would be great if, later on, we could collaborate.

**Comment by macnibblet** [comment]
@axw Collaboration would be awesome. Currently, i'm just messing around trying to figure out how the APM works. And will most likely refactor it a few times before I'm happy with the architecture.

And my plan on integrations with will be to write middleware for HTTP and GRPC servers. 
The initial instrumentations for spans will be.
- go-pg
- go-redis
- elastic

**Comment by macnibblet** [comment]
I think what the go community will want support for is the sql/sqlx/gorm libraries but as soon as we get a clean architecture that allows for simple instrumentations I don't think adding community additions will be a problem.

**Comment by axw** [comment]
@macnibblet sounds like a good set of initial integrations, and I agree that tracing SQL will be a major requirement.

Since you've seen this now, I'll close the issue - just wanted to make sure you knew what was coming. Keep an eye out on Discuss for developments some time later :)

**Comment by axw** [comment]
@macnibblet FYI, the Go agent is now out there: https://github.com/elastic/apm-agent-go. As it says in the docs, it's pre-alpha, which is our way of saying that its API is almost definitely going to change in breaking ways. I've love to hear any feedback you have.
